name: Build plugin zip

on:
  push:
    tags:            # build only when you tag a release, e.g. v1.3
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # create wp-autorag-chatbot.zip (top-level folder = plugin slug)
      - name: Zip plugin
        run: |
          PLUGIN=wp-autorag-chatbot
          mkdir dist
          zip -r dist/${PLUGIN}.zip . \
              -x "*.git*" ".github/*" "tests/*" "composer.*" "package*.json" "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-autorag-chatbot
          path: dist/wp-autorag-chatbot.zip
          retention-days: 30

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/wp-autorag-chatbot.zip

